package es.jclm.cs.rarasclm.entities;
// Generated 10-ago-2016 9:15:45 by Hibernate Tools 4.3.4.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * HistoriaClinica generated by hbm2java
 */
@Entity
@Table(name = "historia_clinica")
public class HistoriaClinica implements java.io.Serializable {

	private HistoriaClinicaId id;
	private Hospital hospital;
	private Paciente paciente;
	private String idUnicoHc;

	public HistoriaClinica() {
	}

	public HistoriaClinica(HistoriaClinicaId id, Hospital hospital, Paciente paciente) {
		this.id = id;
		this.hospital = hospital;
		this.paciente = paciente;
	}

	public HistoriaClinica(HistoriaClinicaId id, Hospital hospital, Paciente paciente, String idUnicoHc) {
		this.id = id;
		this.hospital = hospital;
		this.paciente = paciente;
		this.idUnicoHc = idUnicoHc;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "paciente", column = @Column(name = "paciente", nullable = false)),
			@AttributeOverride(name = "hospital", column = @Column(name = "hospital", nullable = false, length = 6)),
			@AttributeOverride(name = "nhc", column = @Column(name = "nhc", nullable = false, length = 12)) })
	public HistoriaClinicaId getId() {
		return this.id;
	}

	public void setId(HistoriaClinicaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "hospital", nullable = false, insertable = false, updatable = false)
	public Hospital getHospital() {
		return this.hospital;
	}

	public void setHospital(Hospital hospital) {
		this.hospital = hospital;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "paciente", nullable = false, insertable = false, updatable = false)
	public Paciente getPaciente() {
		return this.paciente;
	}

	public void setPaciente(Paciente paciente) {
		this.paciente = paciente;
	}

	@Column(name = "id_unico_hc", length = 18)
	public String getIdUnicoHc() {
		return this.idUnicoHc;
	}

	public void setIdUnicoHc(String idUnicoHc) {
		this.idUnicoHc = idUnicoHc;
	}

}
