package es.jclm.cs.rarasclm.entities;
// Generated 05-jun-2016 17:26:24 by Hibernate Tools 4.3.1.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.OrderBy;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Paciente generated by hbm2java
 */
@Entity
@Table(name = "paciente", catalog = "RARASCLM")
public class Paciente implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5806418133875577789L;
	private int idPaciente;
	private String idpacnac;
	private String cip;
	private String dni;
	private String numeroSegSocial;
	private String nombre;
	private String apellido01;
	private String apellido02;
	private Date fechaNacimiento;
	private Character sexo;
	private String provinciaNacimiento;
	private String municipioNacimiento;
	private String paisNacimiento;
	private String domTipoVia;
	private String domNombreVia;
	private String domNumero;
	private String domPisopuerta;
	private String domOtros;
	private String domCp;
	private String provinciaResidencia;
	private String municipioResidencia;
	private Byte fallecido;
	private Date fallecidoFechaComprobacion;
	private String fallecidoEtiquetaComprobacion;
	private String fallecidoNumbol;
	private String email;
	private String telefono;
	private List<Caso> casos = new ArrayList<Caso>(0);
	private Set<HistoriasClinicas> historiasClinicas = new HashSet<HistoriasClinicas>(0);

	public Paciente() {
	}

	public Paciente(int idPaciente) {
		this.idPaciente = idPaciente;
	}

	public Paciente(int idPaciente, String idpacnac, String cip, String dni, String numeroSegSocial, String nombre,
			String apellido01, String apellido02, Date fechaNacimiento, Character sexo, String provinciaNacimiento,
			String municipioNacimiento, String paisNacimiento, String domTipoVia, String domNombreVia, String domNumero,
			String domPisopuerta, String domOtros, String provinciaResidencia, String municipioResidencia,
			Byte fallecido, Date fallecidoFechaComprobacion, String fallecidoEtiquetaComprobacion,
			String fallecidoNumbol, String email, String telefono, List<Caso> casos,  Set<HistoriasClinicas> historiasClinicases, String domCp) {
		this.idPaciente = idPaciente;
		this.idpacnac = idpacnac;
		this.cip = cip;
		this.dni = dni;
		this.numeroSegSocial = numeroSegSocial;
		this.nombre = nombre;
		this.apellido01 = apellido01;
		this.apellido02 = apellido02;
		this.fechaNacimiento = fechaNacimiento;
		this.sexo = sexo;
		this.provinciaNacimiento = provinciaNacimiento;
		this.municipioNacimiento = municipioNacimiento;
		this.paisNacimiento = paisNacimiento;
		this.domTipoVia = domTipoVia;
		this.domNombreVia = domNombreVia;
		this.domNumero = domNumero;
		this.domPisopuerta = domPisopuerta;
		this.domOtros = domOtros;
		this.provinciaResidencia = provinciaResidencia;
		this.municipioResidencia = municipioResidencia;
		this.fallecido = fallecido;
		this.fallecidoFechaComprobacion = fallecidoFechaComprobacion;
		this.fallecidoEtiquetaComprobacion = fallecidoEtiquetaComprobacion;
		this.fallecidoNumbol = fallecidoNumbol;
		this.email = email;
		this.telefono = telefono;
		this.casos = casos;
		this.historiasClinicas = historiasClinicases;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#getIdPaciente()
	 */
	
	@Id
	@Column(name = "id_paciente", unique = true, nullable = false)
	public int getIdPaciente() {
		return this.idPaciente;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#setIdPaciente(int)
	 */
	
	public void setIdPaciente(int idPaciente) {
		this.idPaciente = idPaciente;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#getIdpacnac()
	 */
	
	@Column(name = "idpacnac", length = 10)
	public String getIdpacnac() {
		return this.idpacnac;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#setIdpacnac(java.lang.String)
	 */
	
	public void setIdpacnac(String idpacnac) {
		this.idpacnac = idpacnac;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#getCip()
	 */
	
	@Column(name = "cip", length = 16)
	public String getCip() {
		return this.cip;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#setCip(java.lang.String)
	 */
	
	public void setCip(String cip) {
		this.cip = cip;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#getDni()
	 */
	
	@Column(name = "dni", length = 12)
	public String getDni() {
		return this.dni;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#setDni(java.lang.String)
	 */
	
	public void setDni(String dni) {
		this.dni = dni;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#getNumeroSegSocial()
	 */
	
	@Column(name = "numero_seg_social", length = 25)
	public String getNumeroSegSocial() {
		return this.numeroSegSocial;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#setNumeroSegSocial(java.lang.String)
	 */
	
	public void setNumeroSegSocial(String numeroSegSocial) {
		this.numeroSegSocial = numeroSegSocial;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#getNombre()
	 */
	
	@Column(name = "nombre", length = 60)
	public String getNombre() {
		return this.nombre;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#setNombre(java.lang.String)
	 */
	
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#getApellido01()
	 */
	
	@Column(name = "apellido_01", length = 60)
	public String getApellido01() {
		return this.apellido01;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#setApellido01(java.lang.String)
	 */
	
	public void setApellido01(String apellido01) {
		this.apellido01 = apellido01;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#getApellido02()
	 */
	
	@Column(name = "apellido_02", length = 60)
	public String getApellido02() {
		return this.apellido02;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#setApellido02(java.lang.String)
	 */
	
	public void setApellido02(String apellido02) {
		this.apellido02 = apellido02;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#getFechaNacimiento()
	 */
	
	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_nacimiento", length = 10)
	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#setFechaNacimiento(java.util.Date)
	 */
	
	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#getSexo()
	 */
	
	@Column(name = "sexo", length = 1)
	public Character getSexo() {
		return this.sexo;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#setSexo(java.lang.Character)
	 */
	
	public void setSexo(Character sexo) {
		this.sexo = sexo;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#getProvinciaNacimiento()
	 */
	
	@Column(name = "provincia_nacimiento", length = 2)
	public String getProvinciaNacimiento() {
		return this.provinciaNacimiento;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#setProvinciaNacimiento(java.lang.String)
	 */
	
	public void setProvinciaNacimiento(String provinciaNacimiento) {
		this.provinciaNacimiento = provinciaNacimiento;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#getMunicipioNacimiento()
	 */
	
	@Column(name = "municipio_nacimiento", length = 5)
	public String getMunicipioNacimiento() {
		return this.municipioNacimiento;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#setMunicipioNacimiento(java.lang.String)
	 */
	
	public void setMunicipioNacimiento(String municipioNacimiento) {
		this.municipioNacimiento = municipioNacimiento;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#getPaisNacimiento()
	 */
	
	@Column(name = "pais_nacimiento", length = 3)
	public String getPaisNacimiento() {
		return this.paisNacimiento;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#setPaisNacimiento(java.lang.String)
	 */
	
	public void setPaisNacimiento(String paisNacimiento) {
		this.paisNacimiento = paisNacimiento;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#getDomTipoVia()
	 */
	
	@Column(name = "dom_tipo_via", length = 6)
	public String getDomTipoVia() {
		return this.domTipoVia;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#setDomTipoVia(java.lang.String)
	 */
	
	public void setDomTipoVia(String domTipoVia) {
		this.domTipoVia = domTipoVia;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#getDomNombreVia()
	 */
	
	@Column(name = "dom_nombre_via", length = 60)
	public String getDomNombreVia() {
		return this.domNombreVia;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#setDomNombreVia(java.lang.String)
	 */
	
	public void setDomNombreVia(String domNombreVia) {
		this.domNombreVia = domNombreVia;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#getDomNumero()
	 */
	
	@Column(name = "dom_numero", length = 4)
	public String getDomNumero() {
		return this.domNumero;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#setDomNumero(java.lang.String)
	 */
	
	public void setDomNumero(String domNumero) {
		this.domNumero = domNumero;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#getDomPisopuerta()
	 */
	
	@Column(name = "dom_pisopuerta", length = 4)
	public String getDomPisopuerta() {
		return this.domPisopuerta;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#setDomPisopuerta(java.lang.String)
	 */
	
	public void setDomPisopuerta(String domPisopuerta) {
		this.domPisopuerta = domPisopuerta;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#getDomOtros()
	 */
	
	@Column(name = "dom_otros", length = 60)
	public String getDomOtros() {
		return this.domOtros;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#setDomOtros(java.lang.String)
	 */
	
	public void setDomOtros(String domOtros) {
		this.domOtros = domOtros;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#getDomCp()
	 */
	
	@Column(name = "dom_cp", length = 5)
	public String getDomCp() {
		return domCp;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#setDomCp(java.lang.String)
	 */
	
	public void setDomCp(String domCp) {
		this.domCp = domCp;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#getProvinciaResidencia()
	 */
	
	@Column(name = "provincia_residencia", length = 2)
	public String getProvinciaResidencia() {
		return this.provinciaResidencia;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#setProvinciaResidencia(java.lang.String)
	 */
	
	public void setProvinciaResidencia(String provinciaResidencia) {
		this.provinciaResidencia = provinciaResidencia;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#getMunicipioResidencia()
	 */
	
	@Column(name = "municipio_residencia", length = 5)
	public String getMunicipioResidencia() {
		return this.municipioResidencia;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#setMunicipioResidencia(java.lang.String)
	 */
	
	public void setMunicipioResidencia(String municipioResidencia) {
		this.municipioResidencia = municipioResidencia;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#getFallecido()
	 */
	
	@Column(name = "fallecido")
	public Byte getFallecido() {
		return this.fallecido;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#setFallecido(java.lang.Byte)
	 */
	
	public void setFallecido(Byte fallecido) {
		this.fallecido = fallecido;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#getFallecidoFechaComprobacion()
	 */
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fallecido_fecha_comprobacion", length = 19)
	public Date getFallecidoFechaComprobacion() {
		return this.fallecidoFechaComprobacion;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#setFallecidoFechaComprobacion(java.util.Date)
	 */
	
	public void setFallecidoFechaComprobacion(Date fallecidoFechaComprobacion) {
		this.fallecidoFechaComprobacion = fallecidoFechaComprobacion;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#getFallecidoEtiquetaComprobacion()
	 */
	
	@Column(name = "fallecido_etiqueta_comprobacion", length = 45)
	public String getFallecidoEtiquetaComprobacion() {
		return this.fallecidoEtiquetaComprobacion;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#setFallecidoEtiquetaComprobacion(java.lang.String)
	 */
	
	public void setFallecidoEtiquetaComprobacion(String fallecidoEtiquetaComprobacion) {
		this.fallecidoEtiquetaComprobacion = fallecidoEtiquetaComprobacion;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#getFallecidoNumbol()
	 */
	
	@Column(name = "fallecido_numbol", length = 10)
	public String getFallecidoNumbol() {
		return this.fallecidoNumbol;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#setFallecidoNumbol(java.lang.String)
	 */
	
	public void setFallecidoNumbol(String fallecidoNumbol) {
		this.fallecidoNumbol = fallecidoNumbol;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#getEmail()
	 */
	
	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#setEmail(java.lang.String)
	 */
	
	public void setEmail(String email) {
		this.email = email;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#getTelefono()
	 */
	
	@Column(name = "telefono", length = 12)
	public String getTelefono() {
		return this.telefono;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#setTelefono(java.lang.String)
	 */
	
	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#getCasos()
	 */
	@JsonIgnore
	@OrderBy(clause = "numCaso")
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "paciente")
	public List<Caso> getCasos() {
		return this.casos;
	}

	/* (non-Javadoc)
	 * @see es.jclm.cs.rarasclm.entities.IPaciente#setCasos(java.util.Set)
	 */
	public void setCasos(List<Caso> casos) {
		this.casos = casos;
	}

	
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "paciente")
	public Set<HistoriasClinicas> getHistoriasClinicas() {
		return historiasClinicas;
	}

	public void setHistoriasClinicas(Set<HistoriasClinicas> historiasClinicas) {
		this.historiasClinicas = historiasClinicas;
	}
	
	

}
