package es.jclm.cs.rarasclm.entities;
// Generated 28-may-2016 19:18:02 by Hibernate Tools 4.3.1.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.OrderBy;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Provincias generated by hbm2java
 */
@Entity
@Table(name = "provincias", catalog = "RARASCLM")
@JsonIgnoreProperties(ignoreUnknown=true)
public class Provincias implements java.io.Serializable {

	private String provincia;
	private Ccaa ccaa;
	private String deno;
	private List<Municipios> municipioses = new ArrayList<Municipios>(0);

	public Provincias() {
	}

	public Provincias(String provincia) {
		this.provincia = provincia;
	}

	public Provincias(String provincia, Ccaa ccaa, String deno, List<Municipios> municipioses) {
		this.provincia = provincia;
		this.ccaa = ccaa;
		this.deno = deno;
		this.municipioses = municipioses;
	}

	@Id
	@Column(name = "provincia", unique = true, nullable = false, length = 2)
	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ccaa")
	public Ccaa getCcaa() {
		return this.ccaa;
	}

	public void setCcaa(Ccaa ccaa) {
		this.ccaa = ccaa;
	}

	@Column(name = "deno", length = 70)
	public String getDeno() {
		return this.deno;
	}

	public void setDeno(String deno) {
		this.deno = deno;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "provincias")
	@OrderBy(clause="deno ASC")
	public List<Municipios> getMunicipioses() {
		return this.municipioses;
	}

	public void setMunicipioses(List<Municipios> municipioses) {
		this.municipioses = municipioses;
	}

}
