package es.jclm.cs.rarasclm.entities;
// Generated 17-may-2016 18:21:10 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name = "roles", catalog = "rarasclm")
public class RolesRarasCLM implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5472292294854231895L;
	/**
	 * 
	 */
	private int id;
	private String deno;
	private Set<UserRarasCLM> userses = new HashSet<UserRarasCLM>(0);

	public RolesRarasCLM() {
	}

	public RolesRarasCLM(int id, String deno) {
		this.id = id;
		this.deno = deno;
	}

	public RolesRarasCLM(int id, String deno, Set<UserRarasCLM> userses) {
		this.id = id;
		this.deno = deno;
		this.userses = userses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "deno", nullable = false, length = 45)
	public String getDeno() {
		return this.deno;
	}

	public void setDeno(String deno) {
		this.deno = deno;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "roleses")
	public Set<UserRarasCLM> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<UserRarasCLM> userses) {
		this.userses = userses;
	}

}
