package es.jclm.cs.rarasclm.entities;
// Generated 13-ago-2016 9:31:52 by Hibernate Tools 4.3.4.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Seccion generated by hbm2java
 */
@Entity
@Table(name = "seccion")
public class Seccion implements java.io.Serializable {

	private int idSeccion;
	private String deno;
	private Set<Caso> casos = new HashSet<Caso>(0);

	public Seccion() {
	}

	public Seccion(int idSeccion) {
		this.idSeccion = idSeccion;
	}

	public Seccion(int idSeccion, String deno, Set<Caso> casos) {
		this.idSeccion = idSeccion;
		this.deno = deno;
		this.casos = casos;
	}

	@Id

	@Column(name = "id_seccion", unique = true, nullable = false)
	public int getIdSeccion() {
		return this.idSeccion;
	}

	public void setIdSeccion(int idSeccion) {
		this.idSeccion = idSeccion;
	}

	@Column(name = "deno", length = 45)
	public String getDeno() {
		return this.deno;
	}

	public void setDeno(String deno) {
		this.deno = deno;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "seccion")
	public Set<Caso> getCasos() {
		return this.casos;
	}

	public void setCasos(Set<Caso> casos) {
		this.casos = casos;
	}

}
