package es.jclm.cs.rarasclm.entities;
// Generated 17-may-2016 18:21:10 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "RARASCLM")
public class UserRarasCLM implements java.io.Serializable {

	
	/**
	 * 
	 */
	private static final long serialVersionUID = 914809243492723834L;
	private String username;
	private String password;
	private byte enabled;
	private Set<RolesRarasCLM> roleses = new HashSet<RolesRarasCLM>(0);

	public UserRarasCLM() {
	}

	public UserRarasCLM(String username, String password, byte enabled) {
		this.username = username;
		this.password = password;
		this.enabled = enabled;
	}

	public UserRarasCLM(String username, String password, byte enabled, Set<RolesRarasCLM> roleses) {
		this.username = username;
		this.password = password;
		this.enabled = enabled;
		this.roleses = roleses;
	}

	@Id
	@Column(name = "username", unique = true, nullable = false, length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 60)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "enabled", nullable = false)
	public byte getEnabled() {
		return this.enabled;
	}

	public void setEnabled(byte enabled) {
		this.enabled = enabled;
	}
	
	public boolean isEnabled()
	{
		return this.enabled>0;
	}
	
	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "user_role", catalog = "RARASCLM", joinColumns = {
			@JoinColumn(name = "username", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "user_rol", nullable = false, updatable = false) })
	public Set<RolesRarasCLM> getRoleses() {
		return this.roleses;
	}

	public void setRoleses(Set<RolesRarasCLM> roleses) {
		this.roleses = roleses;
	}

}
