package es.jclm.cs.rarasclm.entities;
// Generated 14-jun-2016 13:22:23 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EnfermedadRaraHasEnfermedadRaraOminId generated by hbm2java
 */
@Embeddable
public class EnfermedadRaraHasEnfermedadRaraOminId implements java.io.Serializable {

	private String enfermedadRaraId;
	private String ominId;

	public EnfermedadRaraHasEnfermedadRaraOminId() {
	}

	public EnfermedadRaraHasEnfermedadRaraOminId(String enfermedadRaraId, String ominId) {
		this.enfermedadRaraId = enfermedadRaraId;
		this.ominId = ominId;
	}

	@Column(name = "enfermedad_rara_id", nullable = false, length = 10)
	public String getEnfermedadRaraId() {
		return this.enfermedadRaraId;
	}

	public void setEnfermedadRaraId(String enfermedadRaraId) {
		this.enfermedadRaraId = enfermedadRaraId;
	}

	@Column(name = "omin_id", nullable = false, length = 10)
	public String getOminId() {
		return this.ominId;
	}

	public void setOminId(String ominId) {
		this.ominId = ominId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EnfermedadRaraHasEnfermedadRaraOminId))
			return false;
		EnfermedadRaraHasEnfermedadRaraOminId castOther = (EnfermedadRaraHasEnfermedadRaraOminId) other;

		return ((this.getEnfermedadRaraId() == castOther.getEnfermedadRaraId())
				|| (this.getEnfermedadRaraId() != null && castOther.getEnfermedadRaraId() != null
						&& this.getEnfermedadRaraId().equals(castOther.getEnfermedadRaraId())))
				&& ((this.getOminId() == castOther.getOminId()) || (this.getOminId() != null
						&& castOther.getOminId() != null && this.getOminId().equals(castOther.getOminId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getEnfermedadRaraId() == null ? 0 : this.getEnfermedadRaraId().hashCode());
		result = 37 * result + (getOminId() == null ? 0 : this.getOminId().hashCode());
		return result;
	}

}
