package es.jclm.cs.rarasclm.entities;
// Generated 14-jun-2016 13:22:23 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Hospital generated by hbm2java
 */
@Entity
@Table(name = "hospital", catalog = "RARASCLM")
public class Hospital implements java.io.Serializable {

	private String idHospital;
	private String literal;

	public Hospital() {
	}

	public Hospital(String idHospital) {
		this.idHospital = idHospital;
	}

	public Hospital(String idHospital, String literal) {
		this.idHospital = idHospital;
		this.literal = literal;
	}

	@Id

	@Column(name = "id_hospital", unique = true, nullable = false, length = 6)
	public String getIdHospital() {
		return this.idHospital;
	}

	public void setIdHospital(String idHospital) {
		this.idHospital = idHospital;
	}

	@Column(name = "literal", length = 250)
	public String getLiteral() {
		return this.literal;
	}

	public void setLiteral(String literal) {
		this.literal = literal;
	}

}
