package es.jclm.cs.rarasclm.entities;
// Generated 18-jun-2016 4:04:46 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CasoHistoriaId generated by hbm2java
 */
@Embeddable
public class CasoHistoriaId implements java.io.Serializable {

	private String idCaso;
	private int idVersion;

	public CasoHistoriaId() {
	}

	public CasoHistoriaId(String idCaso, int idVersion) {
		this.idCaso = idCaso;
		this.idVersion = idVersion;
	}

	@Column(name = "id_caso", nullable = false, length = 10)
	public String getIdCaso() {
		return this.idCaso;
	}

	public void setIdCaso(String idCaso) {
		this.idCaso = idCaso;
	}

	@Column(name = "id_version", nullable = false)
	public int getIdVersion() {
		return this.idVersion;
	}

	public void setIdVersion(int idVersion) {
		this.idVersion = idVersion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CasoHistoriaId))
			return false;
		CasoHistoriaId castOther = (CasoHistoriaId) other;

		return ((this.getIdCaso() == castOther.getIdCaso()) || (this.getIdCaso() != null
				&& castOther.getIdCaso() != null && this.getIdCaso().equals(castOther.getIdCaso())))
				&& (this.getIdVersion() == castOther.getIdVersion());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdCaso() == null ? 0 : this.getIdCaso().hashCode());
		result = 37 * result + this.getIdVersion();
		return result;
	}

}
