package es.jclm.cs.rarasclm.entities;
// Generated 18-jun-2016 4:04:46 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Hospital generated by hbm2java
 */
@Entity
@Table(name = "hospital", catalog = "rarasclm")
public class Hospital implements java.io.Serializable {

	private String idHospital;
	private String literal;
	private Set<HistoriasClinicas> historiasClinicases = new HashSet<HistoriasClinicas>(0);

	public Hospital() {
	}

	public Hospital(String idHospital) {
		this.idHospital = idHospital;
	}

	public Hospital(String idHospital, String literal, Set<HistoriasClinicas> historiasClinicases) {
		this.idHospital = idHospital;
		this.literal = literal;
		this.historiasClinicases = historiasClinicases;
	}

	@Id

	@Column(name = "id_hospital", unique = true, nullable = false, length = 6)
	public String getIdHospital() {
		return this.idHospital;
	}

	public void setIdHospital(String idHospital) {
		this.idHospital = idHospital;
	}

	@Column(name = "literal", length = 250)
	public String getLiteral() {
		return this.literal;
	}

	public void setLiteral(String literal) {
		this.literal = literal;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hospital")
	public Set<HistoriasClinicas> getHistoriasClinicases() {
		return this.historiasClinicases;
	}

	public void setHistoriasClinicases(Set<HistoriasClinicas> historiasClinicases) {
		this.historiasClinicases = historiasClinicases;
	}

}
