package es.jclm.cs.rarasclm.entities;
// Generated 21-oct-2016 11:12:51 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * EnfermedadCie9mc generated by hbm2java
 */
@Entity
@Table(name = "enfermedad_cie9mc", catalog = "rarasclmtest")
public class EnfermedadCie9mc implements java.io.Serializable {

	private String cie9Id;
	private String literal;
	private String url;
	private String notas;
	private Set<EnfermedadRara> enfermedadRaras = new HashSet<EnfermedadRara>(0);

	public EnfermedadCie9mc() {
	}

	public EnfermedadCie9mc(String cie9Id) {
		this.cie9Id = cie9Id;
	}

	public EnfermedadCie9mc(String cie9Id, String literal, String url, String notas,
			Set<EnfermedadRara> enfermedadRaras) {
		this.cie9Id = cie9Id;
		this.literal = literal;
		this.url = url;
		this.notas = notas;
		this.enfermedadRaras = enfermedadRaras;
	}

	@Id

	@Column(name = "cie9_id", unique = true, nullable = false, length = 6)
	public String getCie9Id() {
		return this.cie9Id;
	}

	public void setCie9Id(String cie9Id) {
		this.cie9Id = cie9Id;
	}

	@Column(name = "literal", length = 1255)
	public String getLiteral() {
		return this.literal;
	}

	public void setLiteral(String literal) {
		this.literal = literal;
	}

	@Column(name = "url")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "notas", length = 2048)
	public String getNotas() {
		return this.notas;
	}

	public void setNotas(String notas) {
		this.notas = notas;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "enfermedadCie9mcs")
	public Set<EnfermedadRara> getEnfermedadRaras() {
		return this.enfermedadRaras;
	}

	public void setEnfermedadRaras(Set<EnfermedadRara> enfermedadRaras) {
		this.enfermedadRaras = enfermedadRaras;
	}

}
