package es.jclm.cs.rarasclm.entities;
// Generated 07-nov-2016 13:43:26 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Provincia generated by hbm2java
 */
@Entity
@Table(name = "provincia", catalog = "rarasclmtest")
public class Provincia implements java.io.Serializable {

	private String provincia;
	private Ccaa ccaa;
	private String deno;
	private Set<Municipio> municipios = new HashSet<Municipio>(0);

	public Provincia() {
	}

	public Provincia(String provincia) {
		this.provincia = provincia;
	}

	public Provincia(String provincia, Ccaa ccaa, String deno, Set<Municipio> municipios) {
		this.provincia = provincia;
		this.ccaa = ccaa;
		this.deno = deno;
		this.municipios = municipios;
	}

	@Id

	@Column(name = "provincia", unique = true, nullable = false, length = 2)
	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ccaa")
	public Ccaa getCcaa() {
		return this.ccaa;
	}

	public void setCcaa(Ccaa ccaa) {
		this.ccaa = ccaa;
	}

	@Column(name = "deno", length = 70)
	public String getDeno() {
		return this.deno;
	}

	public void setDeno(String deno) {
		this.deno = deno;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "provincia")
	public Set<Municipio> getMunicipios() {
		return this.municipios;
	}

	public void setMunicipios(Set<Municipio> municipios) {
		this.municipios = municipios;
	}

}
