package es.jclm.cs.rarasclm.entities;
// Generated 21-oct-2016 11:12:51 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VPacienteCasoId generated by hbm2java
 */
@Embeddable
public class VPacienteCasoId implements java.io.Serializable {

	private int idPaciente;
	private Short numCaso;
	private String idpacnac;
	private String cip;
	private String dni;
	private String numeroSegSocial;
	private String nombre;
	private String apellido01;
	private String apellido02;
	private Date fechaNacimiento;
	private Character sexo;
	private String provinciaNacimiento;
	private String municipioNacimiento;
	private String paisNacimiento;
	private String domTipoVia;
	private String domNombreVia;
	private String domNumero;
	private String domPisopuerta;
	private String domOtros;
	private String domCp;
	private String provinciaResidencia;
	private String municipioResidencia;
	private Byte fallecido;
	private Date fallecidoFecha;
	private Date fallecidoFechaComprobacion;
	private String fallecidoEtiquetaComprobacion;
	private String fallecidoNumbol;
	private String email;
	private String telefono;
	private String enfrara;
	private Short declarada;
	private String usuarioDeclara;
	private String literalEnfermedad;
	private String jucioClinico;
	private String observaciones;
	private String hospital;
	private String numeroHistoriaClinica;
	private Byte baseDiagnostico;
	private String fuenteInformacion;
	private Boolean fuentePacientesA;
	private Boolean fuenteCmbdC;
	private Boolean fuenteDefcongD;
	private Boolean fuenteEdoE;
	private Boolean fuenteIsocialesG;
	private Boolean fuenteMhuerfH;
	private Boolean fuenteMetabolN;
	private Boolean fuenteRinvI;
	private Boolean fuenteRmortM;
	private Boolean fuenteRcancerT;
	private Boolean fuenteRenalR;
	private Boolean fuenteHcPrimariaV;
	private Boolean fuenteHcEspecializadaU;
	private Boolean fuenteHcPrimariaMasivaP;
	private Boolean fuenteHcEspecializadaMasivaQ;
	private Boolean fuenteOtrosO;
	private Date fechaInicioSintomas;
	private Date fechaDeteccion;
	private Date fechaDiagnostico;
	private String codCie9mc;
	private String codCie10;
	private String codSnomed;
	private String codOmin;
	private String codEdta;
	private String codOtros;
	private String codOtroDeno;
	private String tratamiento;
	private Byte familiaresEnfermedadesRaras;
	private Short otrasEnfermedadesCronicas;
	private String enfermedadesCronicas;
	private Date casoFechahoraCreacion;
	private Date casoFechahoraModificacion;
	private String casoUsuarioCreacion;
	private String casoUsuarioModificacion;

	public VPacienteCasoId() {
	}

	public VPacienteCasoId(int idPaciente, String enfrara) {
		this.idPaciente = idPaciente;
		this.enfrara = enfrara;
	}

	public VPacienteCasoId(int idPaciente, Short numCaso, String idpacnac, String cip, String dni,
			String numeroSegSocial, String nombre, String apellido01, String apellido02, Date fechaNacimiento,
			Character sexo, String provinciaNacimiento, String municipioNacimiento, String paisNacimiento,
			String domTipoVia, String domNombreVia, String domNumero, String domPisopuerta, String domOtros,
			String domCp, String provinciaResidencia, String municipioResidencia, Byte fallecido, Date fallecidoFecha,
			Date fallecidoFechaComprobacion, String fallecidoEtiquetaComprobacion, String fallecidoNumbol, String email,
			String telefono, String enfrara, Short declarada, String usuarioDeclara, String literalEnfermedad,
			String jucioClinico, String observaciones, String hospital, String numeroHistoriaClinica,
			Byte baseDiagnostico, String fuenteInformacion, Boolean fuentePacientesA, Boolean fuenteCmbdC,
			Boolean fuenteDefcongD, Boolean fuenteEdoE, Boolean fuenteIsocialesG, Boolean fuenteMhuerfH,
			Boolean fuenteMetabolN, Boolean fuenteRinvI, Boolean fuenteRmortM, Boolean fuenteRcancerT,
			Boolean fuenteRenalR, Boolean fuenteHcPrimariaV, Boolean fuenteHcEspecializadaU,
			Boolean fuenteHcPrimariaMasivaP, Boolean fuenteHcEspecializadaMasivaQ, Boolean fuenteOtrosO,
			Date fechaInicioSintomas, Date fechaDeteccion, Date fechaDiagnostico, String codCie9mc, String codCie10,
			String codSnomed, String codOmin, String codEdta, String codOtros, String codOtroDeno, String tratamiento,
			Byte familiaresEnfermedadesRaras, Short otrasEnfermedadesCronicas, String enfermedadesCronicas,
			Date casoFechahoraCreacion, Date casoFechahoraModificacion, String casoUsuarioCreacion,
			String casoUsuarioModificacion) {
		this.idPaciente = idPaciente;
		this.numCaso = numCaso;
		this.idpacnac = idpacnac;
		this.cip = cip;
		this.dni = dni;
		this.numeroSegSocial = numeroSegSocial;
		this.nombre = nombre;
		this.apellido01 = apellido01;
		this.apellido02 = apellido02;
		this.fechaNacimiento = fechaNacimiento;
		this.sexo = sexo;
		this.provinciaNacimiento = provinciaNacimiento;
		this.municipioNacimiento = municipioNacimiento;
		this.paisNacimiento = paisNacimiento;
		this.domTipoVia = domTipoVia;
		this.domNombreVia = domNombreVia;
		this.domNumero = domNumero;
		this.domPisopuerta = domPisopuerta;
		this.domOtros = domOtros;
		this.domCp = domCp;
		this.provinciaResidencia = provinciaResidencia;
		this.municipioResidencia = municipioResidencia;
		this.fallecido = fallecido;
		this.fallecidoFecha = fallecidoFecha;
		this.fallecidoFechaComprobacion = fallecidoFechaComprobacion;
		this.fallecidoEtiquetaComprobacion = fallecidoEtiquetaComprobacion;
		this.fallecidoNumbol = fallecidoNumbol;
		this.email = email;
		this.telefono = telefono;
		this.enfrara = enfrara;
		this.declarada = declarada;
		this.usuarioDeclara = usuarioDeclara;
		this.literalEnfermedad = literalEnfermedad;
		this.jucioClinico = jucioClinico;
		this.observaciones = observaciones;
		this.hospital = hospital;
		this.numeroHistoriaClinica = numeroHistoriaClinica;
		this.baseDiagnostico = baseDiagnostico;
		this.fuenteInformacion = fuenteInformacion;
		this.fuentePacientesA = fuentePacientesA;
		this.fuenteCmbdC = fuenteCmbdC;
		this.fuenteDefcongD = fuenteDefcongD;
		this.fuenteEdoE = fuenteEdoE;
		this.fuenteIsocialesG = fuenteIsocialesG;
		this.fuenteMhuerfH = fuenteMhuerfH;
		this.fuenteMetabolN = fuenteMetabolN;
		this.fuenteRinvI = fuenteRinvI;
		this.fuenteRmortM = fuenteRmortM;
		this.fuenteRcancerT = fuenteRcancerT;
		this.fuenteRenalR = fuenteRenalR;
		this.fuenteHcPrimariaV = fuenteHcPrimariaV;
		this.fuenteHcEspecializadaU = fuenteHcEspecializadaU;
		this.fuenteHcPrimariaMasivaP = fuenteHcPrimariaMasivaP;
		this.fuenteHcEspecializadaMasivaQ = fuenteHcEspecializadaMasivaQ;
		this.fuenteOtrosO = fuenteOtrosO;
		this.fechaInicioSintomas = fechaInicioSintomas;
		this.fechaDeteccion = fechaDeteccion;
		this.fechaDiagnostico = fechaDiagnostico;
		this.codCie9mc = codCie9mc;
		this.codCie10 = codCie10;
		this.codSnomed = codSnomed;
		this.codOmin = codOmin;
		this.codEdta = codEdta;
		this.codOtros = codOtros;
		this.codOtroDeno = codOtroDeno;
		this.tratamiento = tratamiento;
		this.familiaresEnfermedadesRaras = familiaresEnfermedadesRaras;
		this.otrasEnfermedadesCronicas = otrasEnfermedadesCronicas;
		this.enfermedadesCronicas = enfermedadesCronicas;
		this.casoFechahoraCreacion = casoFechahoraCreacion;
		this.casoFechahoraModificacion = casoFechahoraModificacion;
		this.casoUsuarioCreacion = casoUsuarioCreacion;
		this.casoUsuarioModificacion = casoUsuarioModificacion;
	}

	@Column(name = "id_paciente", nullable = false)
	public int getIdPaciente() {
		return this.idPaciente;
	}

	public void setIdPaciente(int idPaciente) {
		this.idPaciente = idPaciente;
	}

	@Column(name = "num_caso")
	public Short getNumCaso() {
		return this.numCaso;
	}

	public void setNumCaso(Short numCaso) {
		this.numCaso = numCaso;
	}

	@Column(name = "idpacnac", length = 10)
	public String getIdpacnac() {
		return this.idpacnac;
	}

	public void setIdpacnac(String idpacnac) {
		this.idpacnac = idpacnac;
	}

	@Column(name = "cip", length = 16)
	public String getCip() {
		return this.cip;
	}

	public void setCip(String cip) {
		this.cip = cip;
	}

	@Column(name = "dni", length = 12)
	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	@Column(name = "numero_seg_social", length = 25)
	public String getNumeroSegSocial() {
		return this.numeroSegSocial;
	}

	public void setNumeroSegSocial(String numeroSegSocial) {
		this.numeroSegSocial = numeroSegSocial;
	}

	@Column(name = "nombre", length = 60)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellido_01", length = 60)
	public String getApellido01() {
		return this.apellido01;
	}

	public void setApellido01(String apellido01) {
		this.apellido01 = apellido01;
	}

	@Column(name = "apellido_02", length = 60)
	public String getApellido02() {
		return this.apellido02;
	}

	public void setApellido02(String apellido02) {
		this.apellido02 = apellido02;
	}

	@Column(name = "fecha_nacimiento", length = 10)
	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	@Column(name = "sexo", length = 1)
	public Character getSexo() {
		return this.sexo;
	}

	public void setSexo(Character sexo) {
		this.sexo = sexo;
	}

	@Column(name = "provincia_nacimiento", length = 2)
	public String getProvinciaNacimiento() {
		return this.provinciaNacimiento;
	}

	public void setProvinciaNacimiento(String provinciaNacimiento) {
		this.provinciaNacimiento = provinciaNacimiento;
	}

	@Column(name = "municipio_nacimiento", length = 5)
	public String getMunicipioNacimiento() {
		return this.municipioNacimiento;
	}

	public void setMunicipioNacimiento(String municipioNacimiento) {
		this.municipioNacimiento = municipioNacimiento;
	}

	@Column(name = "pais_nacimiento", length = 3)
	public String getPaisNacimiento() {
		return this.paisNacimiento;
	}

	public void setPaisNacimiento(String paisNacimiento) {
		this.paisNacimiento = paisNacimiento;
	}

	@Column(name = "dom_tipo_via", length = 6)
	public String getDomTipoVia() {
		return this.domTipoVia;
	}

	public void setDomTipoVia(String domTipoVia) {
		this.domTipoVia = domTipoVia;
	}

	@Column(name = "dom_nombre_via", length = 60)
	public String getDomNombreVia() {
		return this.domNombreVia;
	}

	public void setDomNombreVia(String domNombreVia) {
		this.domNombreVia = domNombreVia;
	}

	@Column(name = "dom_numero", length = 4)
	public String getDomNumero() {
		return this.domNumero;
	}

	public void setDomNumero(String domNumero) {
		this.domNumero = domNumero;
	}

	@Column(name = "dom_pisopuerta", length = 4)
	public String getDomPisopuerta() {
		return this.domPisopuerta;
	}

	public void setDomPisopuerta(String domPisopuerta) {
		this.domPisopuerta = domPisopuerta;
	}

	@Column(name = "dom_otros", length = 60)
	public String getDomOtros() {
		return this.domOtros;
	}

	public void setDomOtros(String domOtros) {
		this.domOtros = domOtros;
	}

	@Column(name = "dom_cp", length = 5)
	public String getDomCp() {
		return this.domCp;
	}

	public void setDomCp(String domCp) {
		this.domCp = domCp;
	}

	@Column(name = "provincia_residencia", length = 2)
	public String getProvinciaResidencia() {
		return this.provinciaResidencia;
	}

	public void setProvinciaResidencia(String provinciaResidencia) {
		this.provinciaResidencia = provinciaResidencia;
	}

	@Column(name = "municipio_residencia", length = 5)
	public String getMunicipioResidencia() {
		return this.municipioResidencia;
	}

	public void setMunicipioResidencia(String municipioResidencia) {
		this.municipioResidencia = municipioResidencia;
	}

	@Column(name = "fallecido")
	public Byte getFallecido() {
		return this.fallecido;
	}

	public void setFallecido(Byte fallecido) {
		this.fallecido = fallecido;
	}

	@Column(name = "fallecido_fecha", length = 10)
	public Date getFallecidoFecha() {
		return this.fallecidoFecha;
	}

	public void setFallecidoFecha(Date fallecidoFecha) {
		this.fallecidoFecha = fallecidoFecha;
	}

	@Column(name = "fallecido_fecha_comprobacion", length = 19)
	public Date getFallecidoFechaComprobacion() {
		return this.fallecidoFechaComprobacion;
	}

	public void setFallecidoFechaComprobacion(Date fallecidoFechaComprobacion) {
		this.fallecidoFechaComprobacion = fallecidoFechaComprobacion;
	}

	@Column(name = "fallecido_etiqueta_comprobacion", length = 45)
	public String getFallecidoEtiquetaComprobacion() {
		return this.fallecidoEtiquetaComprobacion;
	}

	public void setFallecidoEtiquetaComprobacion(String fallecidoEtiquetaComprobacion) {
		this.fallecidoEtiquetaComprobacion = fallecidoEtiquetaComprobacion;
	}

	@Column(name = "fallecido_numbol", length = 10)
	public String getFallecidoNumbol() {
		return this.fallecidoNumbol;
	}

	public void setFallecidoNumbol(String fallecidoNumbol) {
		this.fallecidoNumbol = fallecidoNumbol;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "telefono", length = 12)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "enfrara", nullable = false, length = 10)
	public String getEnfrara() {
		return this.enfrara;
	}

	public void setEnfrara(String enfrara) {
		this.enfrara = enfrara;
	}

	@Column(name = "declarada")
	public Short getDeclarada() {
		return this.declarada;
	}

	public void setDeclarada(Short declarada) {
		this.declarada = declarada;
	}

	@Column(name = "usuario_declara", length = 45)
	public String getUsuarioDeclara() {
		return this.usuarioDeclara;
	}

	public void setUsuarioDeclara(String usuarioDeclara) {
		this.usuarioDeclara = usuarioDeclara;
	}

	@Column(name = "literal_enfermedad")
	public String getLiteralEnfermedad() {
		return this.literalEnfermedad;
	}

	public void setLiteralEnfermedad(String literalEnfermedad) {
		this.literalEnfermedad = literalEnfermedad;
	}

	@Column(name = "jucio_clinico", length = 1014)
	public String getJucioClinico() {
		return this.jucioClinico;
	}

	public void setJucioClinico(String jucioClinico) {
		this.jucioClinico = jucioClinico;
	}

	@Column(name = "observaciones", length = 4096)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@Column(name = "hospital", length = 6)
	public String getHospital() {
		return this.hospital;
	}

	public void setHospital(String hospital) {
		this.hospital = hospital;
	}

	@Column(name = "numero_historia_clinica", length = 12)
	public String getNumeroHistoriaClinica() {
		return this.numeroHistoriaClinica;
	}

	public void setNumeroHistoriaClinica(String numeroHistoriaClinica) {
		this.numeroHistoriaClinica = numeroHistoriaClinica;
	}

	@Column(name = "base_diagnostico")
	public Byte getBaseDiagnostico() {
		return this.baseDiagnostico;
	}

	public void setBaseDiagnostico(Byte baseDiagnostico) {
		this.baseDiagnostico = baseDiagnostico;
	}

	@Column(name = "fuente_informacion", length = 20)
	public String getFuenteInformacion() {
		return this.fuenteInformacion;
	}

	public void setFuenteInformacion(String fuenteInformacion) {
		this.fuenteInformacion = fuenteInformacion;
	}

	@Column(name = "fuente_pacientes_A")
	public Boolean getFuentePacientesA() {
		return this.fuentePacientesA;
	}

	public void setFuentePacientesA(Boolean fuentePacientesA) {
		this.fuentePacientesA = fuentePacientesA;
	}

	@Column(name = "fuente_cmbd_C")
	public Boolean getFuenteCmbdC() {
		return this.fuenteCmbdC;
	}

	public void setFuenteCmbdC(Boolean fuenteCmbdC) {
		this.fuenteCmbdC = fuenteCmbdC;
	}

	@Column(name = "fuente_defcong_D")
	public Boolean getFuenteDefcongD() {
		return this.fuenteDefcongD;
	}

	public void setFuenteDefcongD(Boolean fuenteDefcongD) {
		this.fuenteDefcongD = fuenteDefcongD;
	}

	@Column(name = "fuente_edo_E")
	public Boolean getFuenteEdoE() {
		return this.fuenteEdoE;
	}

	public void setFuenteEdoE(Boolean fuenteEdoE) {
		this.fuenteEdoE = fuenteEdoE;
	}

	@Column(name = "fuente_isociales_G")
	public Boolean getFuenteIsocialesG() {
		return this.fuenteIsocialesG;
	}

	public void setFuenteIsocialesG(Boolean fuenteIsocialesG) {
		this.fuenteIsocialesG = fuenteIsocialesG;
	}

	@Column(name = "fuente_mhuerf_H")
	public Boolean getFuenteMhuerfH() {
		return this.fuenteMhuerfH;
	}

	public void setFuenteMhuerfH(Boolean fuenteMhuerfH) {
		this.fuenteMhuerfH = fuenteMhuerfH;
	}

	@Column(name = "fuente_metabol_N")
	public Boolean getFuenteMetabolN() {
		return this.fuenteMetabolN;
	}

	public void setFuenteMetabolN(Boolean fuenteMetabolN) {
		this.fuenteMetabolN = fuenteMetabolN;
	}

	@Column(name = "fuente_rinv_I")
	public Boolean getFuenteRinvI() {
		return this.fuenteRinvI;
	}

	public void setFuenteRinvI(Boolean fuenteRinvI) {
		this.fuenteRinvI = fuenteRinvI;
	}

	@Column(name = "fuente_rmort_M")
	public Boolean getFuenteRmortM() {
		return this.fuenteRmortM;
	}

	public void setFuenteRmortM(Boolean fuenteRmortM) {
		this.fuenteRmortM = fuenteRmortM;
	}

	@Column(name = "fuente_rcancer_T")
	public Boolean getFuenteRcancerT() {
		return this.fuenteRcancerT;
	}

	public void setFuenteRcancerT(Boolean fuenteRcancerT) {
		this.fuenteRcancerT = fuenteRcancerT;
	}

	@Column(name = "fuente_renal_R")
	public Boolean getFuenteRenalR() {
		return this.fuenteRenalR;
	}

	public void setFuenteRenalR(Boolean fuenteRenalR) {
		this.fuenteRenalR = fuenteRenalR;
	}

	@Column(name = "fuente_hc_primaria_V")
	public Boolean getFuenteHcPrimariaV() {
		return this.fuenteHcPrimariaV;
	}

	public void setFuenteHcPrimariaV(Boolean fuenteHcPrimariaV) {
		this.fuenteHcPrimariaV = fuenteHcPrimariaV;
	}

	@Column(name = "fuente_hc_especializada_U")
	public Boolean getFuenteHcEspecializadaU() {
		return this.fuenteHcEspecializadaU;
	}

	public void setFuenteHcEspecializadaU(Boolean fuenteHcEspecializadaU) {
		this.fuenteHcEspecializadaU = fuenteHcEspecializadaU;
	}

	@Column(name = "fuente_hc_primaria_masiva_P")
	public Boolean getFuenteHcPrimariaMasivaP() {
		return this.fuenteHcPrimariaMasivaP;
	}

	public void setFuenteHcPrimariaMasivaP(Boolean fuenteHcPrimariaMasivaP) {
		this.fuenteHcPrimariaMasivaP = fuenteHcPrimariaMasivaP;
	}

	@Column(name = "fuente_hc_especializada_masiva_Q")
	public Boolean getFuenteHcEspecializadaMasivaQ() {
		return this.fuenteHcEspecializadaMasivaQ;
	}

	public void setFuenteHcEspecializadaMasivaQ(Boolean fuenteHcEspecializadaMasivaQ) {
		this.fuenteHcEspecializadaMasivaQ = fuenteHcEspecializadaMasivaQ;
	}

	@Column(name = "fuente_otros_O")
	public Boolean getFuenteOtrosO() {
		return this.fuenteOtrosO;
	}

	public void setFuenteOtrosO(Boolean fuenteOtrosO) {
		this.fuenteOtrosO = fuenteOtrosO;
	}

	@Column(name = "fecha_inicio_sintomas", length = 10)
	public Date getFechaInicioSintomas() {
		return this.fechaInicioSintomas;
	}

	public void setFechaInicioSintomas(Date fechaInicioSintomas) {
		this.fechaInicioSintomas = fechaInicioSintomas;
	}

	@Column(name = "fecha_deteccion", length = 10)
	public Date getFechaDeteccion() {
		return this.fechaDeteccion;
	}

	public void setFechaDeteccion(Date fechaDeteccion) {
		this.fechaDeteccion = fechaDeteccion;
	}

	@Column(name = "fecha_diagnostico", length = 10)
	public Date getFechaDiagnostico() {
		return this.fechaDiagnostico;
	}

	public void setFechaDiagnostico(Date fechaDiagnostico) {
		this.fechaDiagnostico = fechaDiagnostico;
	}

	@Column(name = "cod_cie9mc", length = 6)
	public String getCodCie9mc() {
		return this.codCie9mc;
	}

	public void setCodCie9mc(String codCie9mc) {
		this.codCie9mc = codCie9mc;
	}

	@Column(name = "cod_cie10", length = 6)
	public String getCodCie10() {
		return this.codCie10;
	}

	public void setCodCie10(String codCie10) {
		this.codCie10 = codCie10;
	}

	@Column(name = "cod_snomed", length = 20)
	public String getCodSnomed() {
		return this.codSnomed;
	}

	public void setCodSnomed(String codSnomed) {
		this.codSnomed = codSnomed;
	}

	@Column(name = "cod_omin", length = 10)
	public String getCodOmin() {
		return this.codOmin;
	}

	public void setCodOmin(String codOmin) {
		this.codOmin = codOmin;
	}

	@Column(name = "cod_edta", length = 10)
	public String getCodEdta() {
		return this.codEdta;
	}

	public void setCodEdta(String codEdta) {
		this.codEdta = codEdta;
	}

	@Column(name = "cod_otros", length = 20)
	public String getCodOtros() {
		return this.codOtros;
	}

	public void setCodOtros(String codOtros) {
		this.codOtros = codOtros;
	}

	@Column(name = "cod_otro_deno", length = 45)
	public String getCodOtroDeno() {
		return this.codOtroDeno;
	}

	public void setCodOtroDeno(String codOtroDeno) {
		this.codOtroDeno = codOtroDeno;
	}

	@Column(name = "tratamiento", length = 4096)
	public String getTratamiento() {
		return this.tratamiento;
	}

	public void setTratamiento(String tratamiento) {
		this.tratamiento = tratamiento;
	}

	@Column(name = "familiares_enfermedades_raras")
	public Byte getFamiliaresEnfermedadesRaras() {
		return this.familiaresEnfermedadesRaras;
	}

	public void setFamiliaresEnfermedadesRaras(Byte familiaresEnfermedadesRaras) {
		this.familiaresEnfermedadesRaras = familiaresEnfermedadesRaras;
	}

	@Column(name = "otras_enfermedades_cronicas")
	public Short getOtrasEnfermedadesCronicas() {
		return this.otrasEnfermedadesCronicas;
	}

	public void setOtrasEnfermedadesCronicas(Short otrasEnfermedadesCronicas) {
		this.otrasEnfermedadesCronicas = otrasEnfermedadesCronicas;
	}

	@Column(name = "enfermedades_cronicas", length = 1024)
	public String getEnfermedadesCronicas() {
		return this.enfermedadesCronicas;
	}

	public void setEnfermedadesCronicas(String enfermedadesCronicas) {
		this.enfermedadesCronicas = enfermedadesCronicas;
	}

	@Column(name = "caso_fechahora_creacion", length = 19)
	public Date getCasoFechahoraCreacion() {
		return this.casoFechahoraCreacion;
	}

	public void setCasoFechahoraCreacion(Date casoFechahoraCreacion) {
		this.casoFechahoraCreacion = casoFechahoraCreacion;
	}

	@Column(name = "caso_fechahora_modificacion", length = 19)
	public Date getCasoFechahoraModificacion() {
		return this.casoFechahoraModificacion;
	}

	public void setCasoFechahoraModificacion(Date casoFechahoraModificacion) {
		this.casoFechahoraModificacion = casoFechahoraModificacion;
	}

	@Column(name = "caso_usuario_creacion", length = 45)
	public String getCasoUsuarioCreacion() {
		return this.casoUsuarioCreacion;
	}

	public void setCasoUsuarioCreacion(String casoUsuarioCreacion) {
		this.casoUsuarioCreacion = casoUsuarioCreacion;
	}

	@Column(name = "caso_usuario_modificacion", length = 45)
	public String getCasoUsuarioModificacion() {
		return this.casoUsuarioModificacion;
	}

	public void setCasoUsuarioModificacion(String casoUsuarioModificacion) {
		this.casoUsuarioModificacion = casoUsuarioModificacion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VPacienteCasoId))
			return false;
		VPacienteCasoId castOther = (VPacienteCasoId) other;

		return (this.getIdPaciente() == castOther.getIdPaciente())
				&& ((this.getNumCaso() == castOther.getNumCaso()) || (this.getNumCaso() != null
						&& castOther.getNumCaso() != null && this.getNumCaso().equals(castOther.getNumCaso())))
				&& ((this.getIdpacnac() == castOther.getIdpacnac()) || (this.getIdpacnac() != null
						&& castOther.getIdpacnac() != null && this.getIdpacnac().equals(castOther.getIdpacnac())))
				&& ((this.getCip() == castOther.getCip()) || (this.getCip() != null && castOther.getCip() != null
						&& this.getCip().equals(castOther.getCip())))
				&& ((this.getDni() == castOther.getDni()) || (this.getDni() != null && castOther.getDni() != null
						&& this.getDni().equals(castOther.getDni())))
				&& ((this.getNumeroSegSocial() == castOther.getNumeroSegSocial())
						|| (this.getNumeroSegSocial() != null && castOther.getNumeroSegSocial() != null
								&& this.getNumeroSegSocial().equals(castOther.getNumeroSegSocial())))
				&& ((this.getNombre() == castOther.getNombre()) || (this.getNombre() != null
						&& castOther.getNombre() != null && this.getNombre().equals(castOther.getNombre())))
				&& ((this.getApellido01() == castOther.getApellido01()) || (this.getApellido01() != null
						&& castOther.getApellido01() != null && this.getApellido01().equals(castOther.getApellido01())))
				&& ((this.getApellido02() == castOther.getApellido02()) || (this.getApellido02() != null
						&& castOther.getApellido02() != null && this.getApellido02().equals(castOther.getApellido02())))
				&& ((this.getFechaNacimiento() == castOther.getFechaNacimiento())
						|| (this.getFechaNacimiento() != null && castOther.getFechaNacimiento() != null
								&& this.getFechaNacimiento().equals(castOther.getFechaNacimiento())))
				&& ((this.getSexo() == castOther.getSexo()) || (this.getSexo() != null && castOther.getSexo() != null
						&& this.getSexo().equals(castOther.getSexo())))
				&& ((this.getProvinciaNacimiento() == castOther.getProvinciaNacimiento())
						|| (this.getProvinciaNacimiento() != null && castOther.getProvinciaNacimiento() != null
								&& this.getProvinciaNacimiento().equals(castOther.getProvinciaNacimiento())))
				&& ((this.getMunicipioNacimiento() == castOther.getMunicipioNacimiento())
						|| (this.getMunicipioNacimiento() != null && castOther.getMunicipioNacimiento() != null
								&& this.getMunicipioNacimiento().equals(castOther.getMunicipioNacimiento())))
				&& ((this.getPaisNacimiento() == castOther.getPaisNacimiento())
						|| (this.getPaisNacimiento() != null && castOther.getPaisNacimiento() != null
								&& this.getPaisNacimiento().equals(castOther.getPaisNacimiento())))
				&& ((this.getDomTipoVia() == castOther.getDomTipoVia()) || (this.getDomTipoVia() != null
						&& castOther.getDomTipoVia() != null && this.getDomTipoVia().equals(castOther.getDomTipoVia())))
				&& ((this.getDomNombreVia() == castOther.getDomNombreVia())
						|| (this.getDomNombreVia() != null && castOther.getDomNombreVia() != null
								&& this.getDomNombreVia().equals(castOther.getDomNombreVia())))
				&& ((this.getDomNumero() == castOther.getDomNumero()) || (this.getDomNumero() != null
						&& castOther.getDomNumero() != null && this.getDomNumero().equals(castOther.getDomNumero())))
				&& ((this.getDomPisopuerta() == castOther.getDomPisopuerta())
						|| (this.getDomPisopuerta() != null && castOther.getDomPisopuerta() != null
								&& this.getDomPisopuerta().equals(castOther.getDomPisopuerta())))
				&& ((this.getDomOtros() == castOther.getDomOtros()) || (this.getDomOtros() != null
						&& castOther.getDomOtros() != null && this.getDomOtros().equals(castOther.getDomOtros())))
				&& ((this.getDomCp() == castOther.getDomCp()) || (this.getDomCp() != null
						&& castOther.getDomCp() != null && this.getDomCp().equals(castOther.getDomCp())))
				&& ((this.getProvinciaResidencia() == castOther.getProvinciaResidencia())
						|| (this.getProvinciaResidencia() != null && castOther.getProvinciaResidencia() != null
								&& this.getProvinciaResidencia().equals(castOther.getProvinciaResidencia())))
				&& ((this.getMunicipioResidencia() == castOther.getMunicipioResidencia())
						|| (this.getMunicipioResidencia() != null && castOther.getMunicipioResidencia() != null
								&& this.getMunicipioResidencia().equals(castOther.getMunicipioResidencia())))
				&& ((this.getFallecido() == castOther.getFallecido()) || (this.getFallecido() != null
						&& castOther.getFallecido() != null && this.getFallecido().equals(castOther.getFallecido())))
				&& ((this.getFallecidoFecha() == castOther.getFallecidoFecha())
						|| (this.getFallecidoFecha() != null && castOther.getFallecidoFecha() != null
								&& this.getFallecidoFecha().equals(castOther.getFallecidoFecha())))
				&& ((this.getFallecidoFechaComprobacion() == castOther.getFallecidoFechaComprobacion())
						|| (this.getFallecidoFechaComprobacion() != null
								&& castOther.getFallecidoFechaComprobacion() != null
								&& this.getFallecidoFechaComprobacion()
										.equals(castOther.getFallecidoFechaComprobacion())))
				&& ((this.getFallecidoEtiquetaComprobacion() == castOther.getFallecidoEtiquetaComprobacion())
						|| (this.getFallecidoEtiquetaComprobacion() != null
								&& castOther.getFallecidoEtiquetaComprobacion() != null
								&& this.getFallecidoEtiquetaComprobacion()
										.equals(castOther.getFallecidoEtiquetaComprobacion())))
				&& ((this.getFallecidoNumbol() == castOther.getFallecidoNumbol())
						|| (this.getFallecidoNumbol() != null && castOther.getFallecidoNumbol() != null
								&& this.getFallecidoNumbol().equals(castOther.getFallecidoNumbol())))
				&& ((this.getEmail() == castOther.getEmail()) || (this.getEmail() != null
						&& castOther.getEmail() != null && this.getEmail().equals(castOther.getEmail())))
				&& ((this.getTelefono() == castOther.getTelefono()) || (this.getTelefono() != null
						&& castOther.getTelefono() != null && this.getTelefono().equals(castOther.getTelefono())))
				&& ((this.getEnfrara() == castOther.getEnfrara()) || (this.getEnfrara() != null
						&& castOther.getEnfrara() != null && this.getEnfrara().equals(castOther.getEnfrara())))
				&& ((this.getDeclarada() == castOther.getDeclarada()) || (this.getDeclarada() != null
						&& castOther.getDeclarada() != null && this.getDeclarada().equals(castOther.getDeclarada())))
				&& ((this.getUsuarioDeclara() == castOther.getUsuarioDeclara())
						|| (this.getUsuarioDeclara() != null && castOther.getUsuarioDeclara() != null
								&& this.getUsuarioDeclara().equals(castOther.getUsuarioDeclara())))
				&& ((this.getLiteralEnfermedad() == castOther.getLiteralEnfermedad())
						|| (this.getLiteralEnfermedad() != null && castOther.getLiteralEnfermedad() != null
								&& this.getLiteralEnfermedad().equals(castOther.getLiteralEnfermedad())))
				&& ((this.getJucioClinico() == castOther.getJucioClinico())
						|| (this.getJucioClinico() != null && castOther.getJucioClinico() != null
								&& this.getJucioClinico().equals(castOther.getJucioClinico())))
				&& ((this.getObservaciones() == castOther.getObservaciones())
						|| (this.getObservaciones() != null && castOther.getObservaciones() != null
								&& this.getObservaciones().equals(castOther.getObservaciones())))
				&& ((this.getHospital() == castOther.getHospital()) || (this.getHospital() != null
						&& castOther.getHospital() != null && this.getHospital().equals(castOther.getHospital())))
				&& ((this.getNumeroHistoriaClinica() == castOther.getNumeroHistoriaClinica())
						|| (this.getNumeroHistoriaClinica() != null && castOther.getNumeroHistoriaClinica() != null
								&& this.getNumeroHistoriaClinica().equals(castOther.getNumeroHistoriaClinica())))
				&& ((this.getBaseDiagnostico() == castOther.getBaseDiagnostico())
						|| (this.getBaseDiagnostico() != null && castOther.getBaseDiagnostico() != null
								&& this.getBaseDiagnostico().equals(castOther.getBaseDiagnostico())))
				&& ((this.getFuenteInformacion() == castOther.getFuenteInformacion())
						|| (this.getFuenteInformacion() != null && castOther.getFuenteInformacion() != null
								&& this.getFuenteInformacion().equals(castOther.getFuenteInformacion())))
				&& ((this.getFuentePacientesA() == castOther.getFuentePacientesA())
						|| (this.getFuentePacientesA() != null && castOther.getFuentePacientesA() != null
								&& this.getFuentePacientesA().equals(castOther.getFuentePacientesA())))
				&& ((this.getFuenteCmbdC() == castOther.getFuenteCmbdC())
						|| (this.getFuenteCmbdC() != null && castOther.getFuenteCmbdC() != null
								&& this.getFuenteCmbdC().equals(castOther.getFuenteCmbdC())))
				&& ((this.getFuenteDefcongD() == castOther.getFuenteDefcongD())
						|| (this.getFuenteDefcongD() != null && castOther.getFuenteDefcongD() != null
								&& this.getFuenteDefcongD().equals(castOther.getFuenteDefcongD())))
				&& ((this.getFuenteEdoE() == castOther.getFuenteEdoE()) || (this.getFuenteEdoE() != null
						&& castOther.getFuenteEdoE() != null && this.getFuenteEdoE().equals(castOther.getFuenteEdoE())))
				&& ((this.getFuenteIsocialesG() == castOther.getFuenteIsocialesG())
						|| (this.getFuenteIsocialesG() != null && castOther.getFuenteIsocialesG() != null
								&& this.getFuenteIsocialesG().equals(castOther.getFuenteIsocialesG())))
				&& ((this.getFuenteMhuerfH() == castOther.getFuenteMhuerfH())
						|| (this.getFuenteMhuerfH() != null && castOther.getFuenteMhuerfH() != null
								&& this.getFuenteMhuerfH().equals(castOther.getFuenteMhuerfH())))
				&& ((this.getFuenteMetabolN() == castOther.getFuenteMetabolN())
						|| (this.getFuenteMetabolN() != null && castOther.getFuenteMetabolN() != null
								&& this.getFuenteMetabolN().equals(castOther.getFuenteMetabolN())))
				&& ((this.getFuenteRinvI() == castOther.getFuenteRinvI())
						|| (this.getFuenteRinvI() != null && castOther.getFuenteRinvI() != null
								&& this.getFuenteRinvI().equals(castOther.getFuenteRinvI())))
				&& ((this.getFuenteRmortM() == castOther.getFuenteRmortM())
						|| (this.getFuenteRmortM() != null && castOther.getFuenteRmortM() != null
								&& this.getFuenteRmortM().equals(castOther.getFuenteRmortM())))
				&& ((this.getFuenteRcancerT() == castOther.getFuenteRcancerT())
						|| (this.getFuenteRcancerT() != null && castOther.getFuenteRcancerT() != null
								&& this.getFuenteRcancerT().equals(castOther.getFuenteRcancerT())))
				&& ((this.getFuenteRenalR() == castOther.getFuenteRenalR())
						|| (this.getFuenteRenalR() != null && castOther.getFuenteRenalR() != null
								&& this.getFuenteRenalR().equals(castOther.getFuenteRenalR())))
				&& ((this.getFuenteHcPrimariaV() == castOther.getFuenteHcPrimariaV())
						|| (this.getFuenteHcPrimariaV() != null && castOther.getFuenteHcPrimariaV() != null
								&& this.getFuenteHcPrimariaV().equals(castOther.getFuenteHcPrimariaV())))
				&& ((this.getFuenteHcEspecializadaU() == castOther.getFuenteHcEspecializadaU())
						|| (this.getFuenteHcEspecializadaU() != null && castOther.getFuenteHcEspecializadaU() != null
								&& this.getFuenteHcEspecializadaU().equals(castOther.getFuenteHcEspecializadaU())))
				&& ((this.getFuenteHcPrimariaMasivaP() == castOther.getFuenteHcPrimariaMasivaP())
						|| (this.getFuenteHcPrimariaMasivaP() != null && castOther.getFuenteHcPrimariaMasivaP() != null
								&& this.getFuenteHcPrimariaMasivaP().equals(castOther.getFuenteHcPrimariaMasivaP())))
				&& ((this.getFuenteHcEspecializadaMasivaQ() == castOther.getFuenteHcEspecializadaMasivaQ())
						|| (this.getFuenteHcEspecializadaMasivaQ() != null
								&& castOther.getFuenteHcEspecializadaMasivaQ() != null
								&& this.getFuenteHcEspecializadaMasivaQ()
										.equals(castOther.getFuenteHcEspecializadaMasivaQ())))
				&& ((this.getFuenteOtrosO() == castOther.getFuenteOtrosO())
						|| (this.getFuenteOtrosO() != null && castOther.getFuenteOtrosO() != null
								&& this.getFuenteOtrosO().equals(castOther.getFuenteOtrosO())))
				&& ((this.getFechaInicioSintomas() == castOther.getFechaInicioSintomas())
						|| (this.getFechaInicioSintomas() != null && castOther.getFechaInicioSintomas() != null
								&& this.getFechaInicioSintomas().equals(castOther.getFechaInicioSintomas())))
				&& ((this.getFechaDeteccion() == castOther.getFechaDeteccion())
						|| (this.getFechaDeteccion() != null && castOther.getFechaDeteccion() != null
								&& this.getFechaDeteccion().equals(castOther.getFechaDeteccion())))
				&& ((this.getFechaDiagnostico() == castOther.getFechaDiagnostico())
						|| (this.getFechaDiagnostico() != null && castOther.getFechaDiagnostico() != null
								&& this.getFechaDiagnostico().equals(castOther.getFechaDiagnostico())))
				&& ((this.getCodCie9mc() == castOther.getCodCie9mc()) || (this.getCodCie9mc() != null
						&& castOther.getCodCie9mc() != null && this.getCodCie9mc().equals(castOther.getCodCie9mc())))
				&& ((this.getCodCie10() == castOther.getCodCie10()) || (this.getCodCie10() != null
						&& castOther.getCodCie10() != null && this.getCodCie10().equals(castOther.getCodCie10())))
				&& ((this.getCodSnomed() == castOther.getCodSnomed()) || (this.getCodSnomed() != null
						&& castOther.getCodSnomed() != null && this.getCodSnomed().equals(castOther.getCodSnomed())))
				&& ((this.getCodOmin() == castOther.getCodOmin()) || (this.getCodOmin() != null
						&& castOther.getCodOmin() != null && this.getCodOmin().equals(castOther.getCodOmin())))
				&& ((this.getCodEdta() == castOther.getCodEdta()) || (this.getCodEdta() != null
						&& castOther.getCodEdta() != null && this.getCodEdta().equals(castOther.getCodEdta())))
				&& ((this.getCodOtros() == castOther.getCodOtros()) || (this.getCodOtros() != null
						&& castOther.getCodOtros() != null && this.getCodOtros().equals(castOther.getCodOtros())))
				&& ((this.getCodOtroDeno() == castOther.getCodOtroDeno())
						|| (this.getCodOtroDeno() != null && castOther.getCodOtroDeno() != null
								&& this.getCodOtroDeno().equals(castOther.getCodOtroDeno())))
				&& ((this.getTratamiento() == castOther.getTratamiento())
						|| (this.getTratamiento() != null && castOther.getTratamiento() != null
								&& this.getTratamiento().equals(castOther.getTratamiento())))
				&& ((this.getFamiliaresEnfermedadesRaras() == castOther.getFamiliaresEnfermedadesRaras())
						|| (this.getFamiliaresEnfermedadesRaras() != null
								&& castOther.getFamiliaresEnfermedadesRaras() != null
								&& this.getFamiliaresEnfermedadesRaras()
										.equals(castOther.getFamiliaresEnfermedadesRaras())))
				&& ((this.getOtrasEnfermedadesCronicas() == castOther.getOtrasEnfermedadesCronicas())
						|| (this.getOtrasEnfermedadesCronicas() != null
								&& castOther.getOtrasEnfermedadesCronicas() != null
								&& this.getOtrasEnfermedadesCronicas()
										.equals(castOther.getOtrasEnfermedadesCronicas())))
				&& ((this.getEnfermedadesCronicas() == castOther.getEnfermedadesCronicas())
						|| (this.getEnfermedadesCronicas() != null && castOther.getEnfermedadesCronicas() != null
								&& this.getEnfermedadesCronicas().equals(castOther.getEnfermedadesCronicas())))
				&& ((this.getCasoFechahoraCreacion() == castOther.getCasoFechahoraCreacion())
						|| (this.getCasoFechahoraCreacion() != null && castOther.getCasoFechahoraCreacion() != null
								&& this.getCasoFechahoraCreacion().equals(castOther.getCasoFechahoraCreacion())))
				&& ((this.getCasoFechahoraModificacion() == castOther.getCasoFechahoraModificacion())
						|| (this.getCasoFechahoraModificacion() != null
								&& castOther.getCasoFechahoraModificacion() != null
								&& this.getCasoFechahoraModificacion()
										.equals(castOther.getCasoFechahoraModificacion())))
				&& ((this.getCasoUsuarioCreacion() == castOther.getCasoUsuarioCreacion())
						|| (this.getCasoUsuarioCreacion() != null && castOther.getCasoUsuarioCreacion() != null
								&& this.getCasoUsuarioCreacion().equals(castOther.getCasoUsuarioCreacion())))
				&& ((this.getCasoUsuarioModificacion() == castOther.getCasoUsuarioModificacion())
						|| (this.getCasoUsuarioModificacion() != null && castOther.getCasoUsuarioModificacion() != null
								&& this.getCasoUsuarioModificacion().equals(castOther.getCasoUsuarioModificacion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdPaciente();
		result = 37 * result + (getNumCaso() == null ? 0 : this.getNumCaso().hashCode());
		result = 37 * result + (getIdpacnac() == null ? 0 : this.getIdpacnac().hashCode());
		result = 37 * result + (getCip() == null ? 0 : this.getCip().hashCode());
		result = 37 * result + (getDni() == null ? 0 : this.getDni().hashCode());
		result = 37 * result + (getNumeroSegSocial() == null ? 0 : this.getNumeroSegSocial().hashCode());
		result = 37 * result + (getNombre() == null ? 0 : this.getNombre().hashCode());
		result = 37 * result + (getApellido01() == null ? 0 : this.getApellido01().hashCode());
		result = 37 * result + (getApellido02() == null ? 0 : this.getApellido02().hashCode());
		result = 37 * result + (getFechaNacimiento() == null ? 0 : this.getFechaNacimiento().hashCode());
		result = 37 * result + (getSexo() == null ? 0 : this.getSexo().hashCode());
		result = 37 * result + (getProvinciaNacimiento() == null ? 0 : this.getProvinciaNacimiento().hashCode());
		result = 37 * result + (getMunicipioNacimiento() == null ? 0 : this.getMunicipioNacimiento().hashCode());
		result = 37 * result + (getPaisNacimiento() == null ? 0 : this.getPaisNacimiento().hashCode());
		result = 37 * result + (getDomTipoVia() == null ? 0 : this.getDomTipoVia().hashCode());
		result = 37 * result + (getDomNombreVia() == null ? 0 : this.getDomNombreVia().hashCode());
		result = 37 * result + (getDomNumero() == null ? 0 : this.getDomNumero().hashCode());
		result = 37 * result + (getDomPisopuerta() == null ? 0 : this.getDomPisopuerta().hashCode());
		result = 37 * result + (getDomOtros() == null ? 0 : this.getDomOtros().hashCode());
		result = 37 * result + (getDomCp() == null ? 0 : this.getDomCp().hashCode());
		result = 37 * result + (getProvinciaResidencia() == null ? 0 : this.getProvinciaResidencia().hashCode());
		result = 37 * result + (getMunicipioResidencia() == null ? 0 : this.getMunicipioResidencia().hashCode());
		result = 37 * result + (getFallecido() == null ? 0 : this.getFallecido().hashCode());
		result = 37 * result + (getFallecidoFecha() == null ? 0 : this.getFallecidoFecha().hashCode());
		result = 37 * result
				+ (getFallecidoFechaComprobacion() == null ? 0 : this.getFallecidoFechaComprobacion().hashCode());
		result = 37 * result
				+ (getFallecidoEtiquetaComprobacion() == null ? 0 : this.getFallecidoEtiquetaComprobacion().hashCode());
		result = 37 * result + (getFallecidoNumbol() == null ? 0 : this.getFallecidoNumbol().hashCode());
		result = 37 * result + (getEmail() == null ? 0 : this.getEmail().hashCode());
		result = 37 * result + (getTelefono() == null ? 0 : this.getTelefono().hashCode());
		result = 37 * result + (getEnfrara() == null ? 0 : this.getEnfrara().hashCode());
		result = 37 * result + (getDeclarada() == null ? 0 : this.getDeclarada().hashCode());
		result = 37 * result + (getUsuarioDeclara() == null ? 0 : this.getUsuarioDeclara().hashCode());
		result = 37 * result + (getLiteralEnfermedad() == null ? 0 : this.getLiteralEnfermedad().hashCode());
		result = 37 * result + (getJucioClinico() == null ? 0 : this.getJucioClinico().hashCode());
		result = 37 * result + (getObservaciones() == null ? 0 : this.getObservaciones().hashCode());
		result = 37 * result + (getHospital() == null ? 0 : this.getHospital().hashCode());
		result = 37 * result + (getNumeroHistoriaClinica() == null ? 0 : this.getNumeroHistoriaClinica().hashCode());
		result = 37 * result + (getBaseDiagnostico() == null ? 0 : this.getBaseDiagnostico().hashCode());
		result = 37 * result + (getFuenteInformacion() == null ? 0 : this.getFuenteInformacion().hashCode());
		result = 37 * result + (getFuentePacientesA() == null ? 0 : this.getFuentePacientesA().hashCode());
		result = 37 * result + (getFuenteCmbdC() == null ? 0 : this.getFuenteCmbdC().hashCode());
		result = 37 * result + (getFuenteDefcongD() == null ? 0 : this.getFuenteDefcongD().hashCode());
		result = 37 * result + (getFuenteEdoE() == null ? 0 : this.getFuenteEdoE().hashCode());
		result = 37 * result + (getFuenteIsocialesG() == null ? 0 : this.getFuenteIsocialesG().hashCode());
		result = 37 * result + (getFuenteMhuerfH() == null ? 0 : this.getFuenteMhuerfH().hashCode());
		result = 37 * result + (getFuenteMetabolN() == null ? 0 : this.getFuenteMetabolN().hashCode());
		result = 37 * result + (getFuenteRinvI() == null ? 0 : this.getFuenteRinvI().hashCode());
		result = 37 * result + (getFuenteRmortM() == null ? 0 : this.getFuenteRmortM().hashCode());
		result = 37 * result + (getFuenteRcancerT() == null ? 0 : this.getFuenteRcancerT().hashCode());
		result = 37 * result + (getFuenteRenalR() == null ? 0 : this.getFuenteRenalR().hashCode());
		result = 37 * result + (getFuenteHcPrimariaV() == null ? 0 : this.getFuenteHcPrimariaV().hashCode());
		result = 37 * result + (getFuenteHcEspecializadaU() == null ? 0 : this.getFuenteHcEspecializadaU().hashCode());
		result = 37 * result
				+ (getFuenteHcPrimariaMasivaP() == null ? 0 : this.getFuenteHcPrimariaMasivaP().hashCode());
		result = 37 * result
				+ (getFuenteHcEspecializadaMasivaQ() == null ? 0 : this.getFuenteHcEspecializadaMasivaQ().hashCode());
		result = 37 * result + (getFuenteOtrosO() == null ? 0 : this.getFuenteOtrosO().hashCode());
		result = 37 * result + (getFechaInicioSintomas() == null ? 0 : this.getFechaInicioSintomas().hashCode());
		result = 37 * result + (getFechaDeteccion() == null ? 0 : this.getFechaDeteccion().hashCode());
		result = 37 * result + (getFechaDiagnostico() == null ? 0 : this.getFechaDiagnostico().hashCode());
		result = 37 * result + (getCodCie9mc() == null ? 0 : this.getCodCie9mc().hashCode());
		result = 37 * result + (getCodCie10() == null ? 0 : this.getCodCie10().hashCode());
		result = 37 * result + (getCodSnomed() == null ? 0 : this.getCodSnomed().hashCode());
		result = 37 * result + (getCodOmin() == null ? 0 : this.getCodOmin().hashCode());
		result = 37 * result + (getCodEdta() == null ? 0 : this.getCodEdta().hashCode());
		result = 37 * result + (getCodOtros() == null ? 0 : this.getCodOtros().hashCode());
		result = 37 * result + (getCodOtroDeno() == null ? 0 : this.getCodOtroDeno().hashCode());
		result = 37 * result + (getTratamiento() == null ? 0 : this.getTratamiento().hashCode());
		result = 37 * result
				+ (getFamiliaresEnfermedadesRaras() == null ? 0 : this.getFamiliaresEnfermedadesRaras().hashCode());
		result = 37 * result
				+ (getOtrasEnfermedadesCronicas() == null ? 0 : this.getOtrasEnfermedadesCronicas().hashCode());
		result = 37 * result + (getEnfermedadesCronicas() == null ? 0 : this.getEnfermedadesCronicas().hashCode());
		result = 37 * result + (getCasoFechahoraCreacion() == null ? 0 : this.getCasoFechahoraCreacion().hashCode());
		result = 37 * result
				+ (getCasoFechahoraModificacion() == null ? 0 : this.getCasoFechahoraModificacion().hashCode());
		result = 37 * result + (getCasoUsuarioCreacion() == null ? 0 : this.getCasoUsuarioCreacion().hashCode());
		result = 37 * result
				+ (getCasoUsuarioModificacion() == null ? 0 : this.getCasoUsuarioModificacion().hashCode());
		return result;
	}

}
