package es.jclm.cs.rarasclm.entities;
// Generated 28-may-2016 19:43:36 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EnfermedadRaraSnomed generated by hbm2java
 */
@Entity
@Table(name = "enfermedad_rara_snomed", catalog = "RARASCLM")
public class EnfermedadRaraSnomed implements java.io.Serializable {

	private long snomedId;
	private String literal;
	private String url;
	private Set<EnfermedadRaraHasEnfermedadRaraSnomed> enfermedadRaraHasEnfermedadRaraSnomeds = new HashSet<EnfermedadRaraHasEnfermedadRaraSnomed>(
			0);

	public EnfermedadRaraSnomed() {
	}

	public EnfermedadRaraSnomed(long snomedId) {
		this.snomedId = snomedId;
	}

	public EnfermedadRaraSnomed(long snomedId, String literal, String url,
			Set<EnfermedadRaraHasEnfermedadRaraSnomed> enfermedadRaraHasEnfermedadRaraSnomeds) {
		this.snomedId = snomedId;
		this.literal = literal;
		this.url = url;
		this.enfermedadRaraHasEnfermedadRaraSnomeds = enfermedadRaraHasEnfermedadRaraSnomeds;
	}

	@Id

	@Column(name = "snomed_id", unique = true, nullable = false)
	public long getSnomedId() {
		return this.snomedId;
	}

	public void setSnomedId(long snomedId) {
		this.snomedId = snomedId;
	}

	@Column(name = "literal")
	public String getLiteral() {
		return this.literal;
	}

	public void setLiteral(String literal) {
		this.literal = literal;
	}

	@Column(name = "url")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "enfermedadRaraSnomed")
	public Set<EnfermedadRaraHasEnfermedadRaraSnomed> getEnfermedadRaraHasEnfermedadRaraSnomeds() {
		return this.enfermedadRaraHasEnfermedadRaraSnomeds;
	}

	public void setEnfermedadRaraHasEnfermedadRaraSnomeds(
			Set<EnfermedadRaraHasEnfermedadRaraSnomed> enfermedadRaraHasEnfermedadRaraSnomeds) {
		this.enfermedadRaraHasEnfermedadRaraSnomeds = enfermedadRaraHasEnfermedadRaraSnomeds;
	}

}
