package es.jclm.cs.rarasclm.entities;
// Generated 05-jun-2016 17:26:24 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EnfermedadRenal generated by hbm2java
 */
@Entity
@Table(name = "enfermedad_renal", catalog = "rarasclm")
public class EnfermedadRenal implements java.io.Serializable {

	private String erenalId;
	private String literal;
	private String grupo;
	private String cie1001;
	private String cie1002;
	private String cie1003;
	private String cie1004;
	private String cie1005;
	private String cie1006;
	private String cie1007;
	private Set<EnfermedadRara> enfermedadRaras = new HashSet<EnfermedadRara>(0);

	public EnfermedadRenal() {
	}

	public EnfermedadRenal(String erenalId) {
		this.erenalId = erenalId;
	}

	public EnfermedadRenal(String erenalId, String literal, String grupo, String cie1001, String cie1002,
			String cie1003, String cie1004, String cie1005, String cie1006, String cie1007,
			Set<EnfermedadRara> enfermedadRaras) {
		this.erenalId = erenalId;
		this.literal = literal;
		this.grupo = grupo;
		this.cie1001 = cie1001;
		this.cie1002 = cie1002;
		this.cie1003 = cie1003;
		this.cie1004 = cie1004;
		this.cie1005 = cie1005;
		this.cie1006 = cie1006;
		this.cie1007 = cie1007;
		this.enfermedadRaras = enfermedadRaras;
	}

	@Id

	@Column(name = "erenal_id", unique = true, nullable = false, length = 2)
	public String getErenalId() {
		return this.erenalId;
	}

	public void setErenalId(String erenalId) {
		this.erenalId = erenalId;
	}

	@Column(name = "literal", length = 75)
	public String getLiteral() {
		return this.literal;
	}

	public void setLiteral(String literal) {
		this.literal = literal;
	}

	@Column(name = "grupo", length = 1)
	public String getGrupo() {
		return this.grupo;
	}

	public void setGrupo(String grupo) {
		this.grupo = grupo;
	}

	@Column(name = "cie_10_01", length = 5)
	public String getCie1001() {
		return this.cie1001;
	}

	public void setCie1001(String cie1001) {
		this.cie1001 = cie1001;
	}

	@Column(name = "cie_10_02", length = 5)
	public String getCie1002() {
		return this.cie1002;
	}

	public void setCie1002(String cie1002) {
		this.cie1002 = cie1002;
	}

	@Column(name = "cie_10_03", length = 5)
	public String getCie1003() {
		return this.cie1003;
	}

	public void setCie1003(String cie1003) {
		this.cie1003 = cie1003;
	}

	@Column(name = "cie_10_04", length = 5)
	public String getCie1004() {
		return this.cie1004;
	}

	public void setCie1004(String cie1004) {
		this.cie1004 = cie1004;
	}

	@Column(name = "cie_10_05", length = 5)
	public String getCie1005() {
		return this.cie1005;
	}

	public void setCie1005(String cie1005) {
		this.cie1005 = cie1005;
	}

	@Column(name = "cie_10_06", length = 5)
	public String getCie1006() {
		return this.cie1006;
	}

	public void setCie1006(String cie1006) {
		this.cie1006 = cie1006;
	}

	@Column(name = "cie_10_07", length = 5)
	public String getCie1007() {
		return this.cie1007;
	}

	public void setCie1007(String cie1007) {
		this.cie1007 = cie1007;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "enfermedadRenal")
	public Set<EnfermedadRara> getEnfermedadRaras() {
		return this.enfermedadRaras;
	}

	public void setEnfermedadRaras(Set<EnfermedadRara> enfermedadRaras) {
		this.enfermedadRaras = enfermedadRaras;
	}

}
