package es.jclm.cs.rarasclm.entities;
// Generated 05-jun-2016 17:26:24 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EnfermedadRara generated by hbm2java
 */
@Entity
@Table(name = "enfermedad_rara", catalog = "RARASCLM")
public class EnfermedadRara implements java.io.Serializable {

	private String enfermedadRaraId;
	private EnfermedadRenal enfermedadRenal;
	private String literal;
	private String otroCod;
	private String denoOtro;
	private String descripcion;
	private String url;
	private Date ultimaActualizacion;
	private String notas;
	private Set<EnfermedadRaraHasEnfermedadRaraOrphanet> enfermedadRaraHasEnfermedadRaraOrphanets = new HashSet<EnfermedadRaraHasEnfermedadRaraOrphanet>(
			0);
	private Set<EnfermedadRaraHasEnfermedadRaraCie9mc> enfermedadRaraHasEnfermedadRaraCie9mcs = new HashSet<EnfermedadRaraHasEnfermedadRaraCie9mc>(
			0);
	private Set<EnfermedadRaraHasEnfermedadRaraOmin> enfermedadRaraHasEnfermedadRaraOmins = new HashSet<EnfermedadRaraHasEnfermedadRaraOmin>(
			0);
	private Set<EnfermedadRaraHasEnfermedadRaraCie10> enfermedadRaraHasEnfermedadRaraCie10s = new HashSet<EnfermedadRaraHasEnfermedadRaraCie10>(
			0);
	private Set<EnfermedadRaraHasEnfermedadRaraSnomed> enfermedadRaraHasEnfermedadRaraSnomeds = new HashSet<EnfermedadRaraHasEnfermedadRaraSnomed>(
			0);

	public EnfermedadRara() {
	}

	public EnfermedadRara(String enfermedadRaraId) {
		this.enfermedadRaraId = enfermedadRaraId;
	}

	public EnfermedadRara(String enfermedadRaraId, EnfermedadRenal enfermedadRenal, String literal, String otroCod,
			String denoOtro, String descripcion, String url, Date ultimaActualizacion, String notas,
			Set<EnfermedadRaraHasEnfermedadRaraOrphanet> enfermedadRaraHasEnfermedadRaraOrphanets,
			Set<EnfermedadRaraHasEnfermedadRaraCie9mc> enfermedadRaraHasEnfermedadRaraCie9mcs,
			Set<EnfermedadRaraHasEnfermedadRaraOmin> enfermedadRaraHasEnfermedadRaraOmins,
			Set<EnfermedadRaraHasEnfermedadRaraCie10> enfermedadRaraHasEnfermedadRaraCie10s,
			Set<EnfermedadRaraHasEnfermedadRaraSnomed> enfermedadRaraHasEnfermedadRaraSnomeds) {
		this.enfermedadRaraId = enfermedadRaraId;
		this.enfermedadRenal = enfermedadRenal;
		this.literal = literal;
		this.otroCod = otroCod;
		this.denoOtro = denoOtro;
		this.descripcion = descripcion;
		this.url = url;
		this.ultimaActualizacion = ultimaActualizacion;
		this.notas = notas;
		this.enfermedadRaraHasEnfermedadRaraOrphanets = enfermedadRaraHasEnfermedadRaraOrphanets;
		this.enfermedadRaraHasEnfermedadRaraCie9mcs = enfermedadRaraHasEnfermedadRaraCie9mcs;
		this.enfermedadRaraHasEnfermedadRaraOmins = enfermedadRaraHasEnfermedadRaraOmins;
		this.enfermedadRaraHasEnfermedadRaraCie10s = enfermedadRaraHasEnfermedadRaraCie10s;
		this.enfermedadRaraHasEnfermedadRaraSnomeds = enfermedadRaraHasEnfermedadRaraSnomeds;
	}

	@Id

	@Column(name = "enfermedad_rara_id", unique = true, nullable = false, length = 10)
	public String getEnfermedadRaraId() {
		return this.enfermedadRaraId;
	}

	public void setEnfermedadRaraId(String enfermedadRaraId) {
		this.enfermedadRaraId = enfermedadRaraId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "renal")
	public EnfermedadRenal getEnfermedadRenal() {
		return this.enfermedadRenal;
	}

	public void setEnfermedadRenal(EnfermedadRenal enfermedadRenal) {
		this.enfermedadRenal = enfermedadRenal;
	}

	@Column(name = "literal")
	public String getLiteral() {
		return this.literal;
	}

	public void setLiteral(String literal) {
		this.literal = literal;
	}

	@Column(name = "otro_cod", length = 50)
	public String getOtroCod() {
		return this.otroCod;
	}

	public void setOtroCod(String otroCod) {
		this.otroCod = otroCod;
	}

	@Column(name = "deno_otro", length = 50)
	public String getDenoOtro() {
		return this.denoOtro;
	}

	public void setDenoOtro(String denoOtro) {
		this.denoOtro = denoOtro;
	}

	@Column(name = "descripcion", length = 4000)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "url")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ultima_actualizacion", length = 19)
	public Date getUltimaActualizacion() {
		return this.ultimaActualizacion;
	}

	public void setUltimaActualizacion(Date ultimaActualizacion) {
		this.ultimaActualizacion = ultimaActualizacion;
	}

	@Column(name = "notas")
	public String getNotas() {
		return this.notas;
	}

	public void setNotas(String notas) {
		this.notas = notas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "enfermedadRara")
	public Set<EnfermedadRaraHasEnfermedadRaraOrphanet> getEnfermedadRaraHasEnfermedadRaraOrphanets() {
		return this.enfermedadRaraHasEnfermedadRaraOrphanets;
	}

	public void setEnfermedadRaraHasEnfermedadRaraOrphanets(
			Set<EnfermedadRaraHasEnfermedadRaraOrphanet> enfermedadRaraHasEnfermedadRaraOrphanets) {
		this.enfermedadRaraHasEnfermedadRaraOrphanets = enfermedadRaraHasEnfermedadRaraOrphanets;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "enfermedadRara")
	public Set<EnfermedadRaraHasEnfermedadRaraCie9mc> getEnfermedadRaraHasEnfermedadRaraCie9mcs() {
		return this.enfermedadRaraHasEnfermedadRaraCie9mcs;
	}

	public void setEnfermedadRaraHasEnfermedadRaraCie9mcs(
			Set<EnfermedadRaraHasEnfermedadRaraCie9mc> enfermedadRaraHasEnfermedadRaraCie9mcs) {
		this.enfermedadRaraHasEnfermedadRaraCie9mcs = enfermedadRaraHasEnfermedadRaraCie9mcs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "enfermedadRara")
	public Set<EnfermedadRaraHasEnfermedadRaraOmin> getEnfermedadRaraHasEnfermedadRaraOmins() {
		return this.enfermedadRaraHasEnfermedadRaraOmins;
	}

	public void setEnfermedadRaraHasEnfermedadRaraOmins(
			Set<EnfermedadRaraHasEnfermedadRaraOmin> enfermedadRaraHasEnfermedadRaraOmins) {
		this.enfermedadRaraHasEnfermedadRaraOmins = enfermedadRaraHasEnfermedadRaraOmins;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "enfermedadRara")
	public Set<EnfermedadRaraHasEnfermedadRaraCie10> getEnfermedadRaraHasEnfermedadRaraCie10s() {
		return this.enfermedadRaraHasEnfermedadRaraCie10s;
	}

	public void setEnfermedadRaraHasEnfermedadRaraCie10s(
			Set<EnfermedadRaraHasEnfermedadRaraCie10> enfermedadRaraHasEnfermedadRaraCie10s) {
		this.enfermedadRaraHasEnfermedadRaraCie10s = enfermedadRaraHasEnfermedadRaraCie10s;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "enfermedadRara")
	public Set<EnfermedadRaraHasEnfermedadRaraSnomed> getEnfermedadRaraHasEnfermedadRaraSnomeds() {
		return this.enfermedadRaraHasEnfermedadRaraSnomeds;
	}

	public void setEnfermedadRaraHasEnfermedadRaraSnomeds(
			Set<EnfermedadRaraHasEnfermedadRaraSnomed> enfermedadRaraHasEnfermedadRaraSnomeds) {
		this.enfermedadRaraHasEnfermedadRaraSnomeds = enfermedadRaraHasEnfermedadRaraSnomeds;
	}

}
