package es.jclm.cs.rarasclm.entities;
// Generated 05-jun-2016 17:26:24 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EnfermedadRaraCie9mc generated by hbm2java
 */
@Entity
@Table(name = "enfermedad_rara_cie9mc", catalog = "RARASCLM")
public class EnfermedadRaraCie9mc implements java.io.Serializable {

	private String cie9Id;
	private String literal;
	private String url;
	private String notas;
	private Set<EnfermedadRaraHasEnfermedadRaraCie9mc> enfermedadRaraHasEnfermedadRaraCie9mcs = new HashSet<EnfermedadRaraHasEnfermedadRaraCie9mc>(
			0);

	public EnfermedadRaraCie9mc() {
	}

	public EnfermedadRaraCie9mc(String cie9Id) {
		this.cie9Id = cie9Id;
	}

	public EnfermedadRaraCie9mc(String cie9Id, String literal, String url, String notas,
			Set<EnfermedadRaraHasEnfermedadRaraCie9mc> enfermedadRaraHasEnfermedadRaraCie9mcs) {
		this.cie9Id = cie9Id;
		this.literal = literal;
		this.url = url;
		this.notas = notas;
		this.enfermedadRaraHasEnfermedadRaraCie9mcs = enfermedadRaraHasEnfermedadRaraCie9mcs;
	}

	@Id

	@Column(name = "cie9_id", unique = true, nullable = false, length = 6)
	public String getCie9Id() {
		return this.cie9Id;
	}

	public void setCie9Id(String cie9Id) {
		this.cie9Id = cie9Id;
	}

	@Column(name = "literal", length = 1255)
	public String getLiteral() {
		return this.literal;
	}

	public void setLiteral(String literal) {
		this.literal = literal;
	}

	@Column(name = "url")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "notas", length = 2048)
	public String getNotas() {
		return this.notas;
	}

	public void setNotas(String notas) {
		this.notas = notas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "enfermedadRaraCie9mc")
	public Set<EnfermedadRaraHasEnfermedadRaraCie9mc> getEnfermedadRaraHasEnfermedadRaraCie9mcs() {
		return this.enfermedadRaraHasEnfermedadRaraCie9mcs;
	}

	public void setEnfermedadRaraHasEnfermedadRaraCie9mcs(
			Set<EnfermedadRaraHasEnfermedadRaraCie9mc> enfermedadRaraHasEnfermedadRaraCie9mcs) {
		this.enfermedadRaraHasEnfermedadRaraCie9mcs = enfermedadRaraHasEnfermedadRaraCie9mcs;
	}

}
