package es.jclm.cs.rarasclm.entities;
// Generated 27-may-2016 13:20:43 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EnfermedadRaraHasEnfermedadRaraCie9mcId generated by hbm2java
 */
@Embeddable
public class EnfermedadRaraHasEnfermedadRaraCie9mcId implements java.io.Serializable {

	private String enfermedadRaraId;
	private String cie9Id;

	public EnfermedadRaraHasEnfermedadRaraCie9mcId() {
	}

	public EnfermedadRaraHasEnfermedadRaraCie9mcId(String enfermedadRaraId, String cie9Id) {
		this.enfermedadRaraId = enfermedadRaraId;
		this.cie9Id = cie9Id;
	}

	@Column(name = "enfermedad_rara_id", nullable = false, length = 10)
	public String getEnfermedadRaraId() {
		return this.enfermedadRaraId;
	}

	public void setEnfermedadRaraId(String enfermedadRaraId) {
		this.enfermedadRaraId = enfermedadRaraId;
	}

	@Column(name = "cie9_id", nullable = false, length = 6)
	public String getCie9Id() {
		return this.cie9Id;
	}

	public void setCie9Id(String cie9Id) {
		this.cie9Id = cie9Id;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EnfermedadRaraHasEnfermedadRaraCie9mcId))
			return false;
		EnfermedadRaraHasEnfermedadRaraCie9mcId castOther = (EnfermedadRaraHasEnfermedadRaraCie9mcId) other;

		return ((this.getEnfermedadRaraId() == castOther.getEnfermedadRaraId())
				|| (this.getEnfermedadRaraId() != null && castOther.getEnfermedadRaraId() != null
						&& this.getEnfermedadRaraId().equals(castOther.getEnfermedadRaraId())))
				&& ((this.getCie9Id() == castOther.getCie9Id()) || (this.getCie9Id() != null
						&& castOther.getCie9Id() != null && this.getCie9Id().equals(castOther.getCie9Id())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getEnfermedadRaraId() == null ? 0 : this.getEnfermedadRaraId().hashCode());
		result = 37 * result + (getCie9Id() == null ? 0 : this.getCie9Id().hashCode());
		return result;
	}

}
