package es.jclm.cs.rarasclm.entities;
// Generated 15-jun-2016 6:48:58 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Municipios generated by hbm2java
 */
@Entity
@Table(name = "municipios", catalog = "rarasclm")
public class Municipios implements java.io.Serializable {

	private String municipio;
	private Provincias provincias;
	private String deno;
	private String ccaa;

	public Municipios() {
	}

	public Municipios(String municipio) {
		this.municipio = municipio;
	}

	public Municipios(String municipio, Provincias provincias, String deno, String ccaa) {
		this.municipio = municipio;
		this.provincias = provincias;
		this.deno = deno;
		this.ccaa = ccaa;
	}

	@Id

	@Column(name = "municipio", unique = true, nullable = false, length = 5)
	public String getMunicipio() {
		return this.municipio;
	}

	public void setMunicipio(String municipio) {
		this.municipio = municipio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "provincia")
	public Provincias getProvincias() {
		return this.provincias;
	}

	public void setProvincias(Provincias provincias) {
		this.provincias = provincias;
	}

	@Column(name = "deno", length = 70)
	public String getDeno() {
		return this.deno;
	}

	public void setDeno(String deno) {
		this.deno = deno;
	}

	@Column(name = "ccaa", length = 2)
	public String getCcaa() {
		return this.ccaa;
	}

	public void setCcaa(String ccaa) {
		this.ccaa = ccaa;
	}

}
